namespace TownOfUsFusion
{
    public enum CustomRPC
{
    SetRole = 100,
    SetModifier,
    SetTag,
    SetAlliance,
    SetCouple,
    SetRecruits,
    SetHeretics,
    SetAssassin,
    SetTarget,
    SetGATarget,

    SetPhantom,
    CatchPhantom,

    SetHaunter,
    CatchHaunter,

    SetTraitor,
    TraitorSpawn,

    LoveWin,
    GlitchWin,
    ArsonistWin,
    TaskmasterWin,
    PhantomWin,
    NobodyWins,
    WerewolfWin,
    SentinelWin,
    SentinelCrewWin,
    SurvivorOnlyWin,
    VampireWin,
    CSWin,
    JackalWin,

    CannibalWin,
    NecroWin,
    ApocWin,

    JanitorClean,
    FixLights,
    EngineerFix,
    SetSwaps,
    SoulSwap,
    Protect,
    SetJkTarget,
    AttemptSound,
    Morph,
    Mine,
    Swoop,
    AltruistRevive,
    BarryButton,
    Drag,
    Drop,
    AssassinKill,
    HuskAssassinKill,
    VigilanteKill,
    DoomsayerKill,
    FlashGrenade,
    Alert,
    Remember,
    BaitReport,
    Transport,
    SetUntransportable,
    Mediate,
    Vest,
    GAProtect,
    BGGuard,
    Poison,
    RemoteBite,
    CannibalEat,
    Blackmail,
    Infect,
    TurnPestilence,
    TurnWar,
    Disperse,
    Escape,
    Revive,
    Convert,
    ChameleonSwoop,
    Imitate,
    StartImitate,
    Bite,
    Reveal,
    Prosecute,
    Confess,
    Bless,
    Camouflage,
    SnitchCultistReveal,
    HunterStalk,
    HunterCatchPlayer,
    Retribution,

    BypassKill,
    BypassMultiKill,
    SetMimic,
    RpcResetAnim,
    SetHacked,
    SetStunned,
    SetInverted,

    ExecutionerToJester,
    JokerToJester,
    GAToSurv,
    GuardReset,

    Start,
    SyncCustomSettings,
    FixAnimation,
    SetPos,
    SetSettings,

    RemoveAllBodies,
    CheckMurder,

    SubmergedFixOxygen,
    ContentAddition,

    // TOU FUSION ROLES
    Resurrect,
    Resurrect2,
    NeoConvert,
    Guard,
    AddTyrantVoteBank,
}
}
